refactor: switch to using git subtree instead of splitsh/lite
I had an issue with the python subpackage where it wouldn't allow me to
push to it:

```sh
$ git subtree push --prefix packages/python sdks-python main
git push using:  sdks-python main
To github.com:readmeio/metrics-sdks-python.git
 ! [rejected]        0aa9f321f28aa869dc88113eaab1f28eec0f906c -> main (non-fast-forward)
error: failed to push some refs to 'github.com:readmeio/metrics-sdks-python.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I ended up doing this, with a force push of the subtree to the sdks-python remote
using a subshell: https://stackoverflow.com/a/38000000

```sh
git push sdks-python $(git subtree split --prefix=packages/python main):main --force
```

This seems to have done the trick?