fix: use CJS api SDK instead
fixes this error:

```
/Users/kanadg/Code/readmeio/metrics-sdks/packages/node/.api/apis/developers/index.ts:1
import type * as types from './types';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1124:15)
    at Module._compile (node:internal/modules/cjs/loader:1160:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (metrics-sdks/packages/node/dist/src/index.js:55:36)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
```

might be an api bug?