fix: unified snippet QA (#902)
* chore(node): tidy up types

* test: add better types to testbed

* chore: refresh lockfile

i had to downgrade to npm@7 for this... absolutely cursed

* chore: strict config fixes

* chore: more TS fixes

not sure why VS code didn't flag these the first time 🤔

also i know this is nuts but open to alternatives lol

* chore: use promise.resolve generics

Co-Authored-By: Jon Ursenbach <jon@ursenba.ch>

* test: add test for undefined webhook

Co-Authored-By: Jon Ursenbach <jon@ursenba.ch>

* refactor: consolidate type

this is the shit i live for

* chore: slightly reorganize tsconfigs

* revert: var change

* refactor: add'l stronger types

* refactor: another strict type

Co-Authored-By: Bill Mill <bill@billmill.org>

* refactor: consolidate type

Co-Authored-By: Bill Mill <bill@billmill.org>

* refactor: more type passes

Co-Authored-By: Bill Mill <bill@billmill.org>

* chore: better comment

* chore: another stricter type

Co-Authored-By: Aaron Hedges <218751+Dashron@users.noreply.github.com>

* refactor: clientIPAddress is required

* revert: oops didn't mean to commit this

* refactor: stricter typing for headers and method

* chore: ts cleanup in test-verify-webhook file

* refactor(setup readme view): use crypto, TS cleanup

* chore: lint

* refactor: some low hanging fruit in index.ts

* chore: initial commit of example repo

* chore: replace snippet with marc's snippet

source: https://gist.github.com/mjcuva/c23a7c08d9528eeb8687ab83132622c1

* fix: some fixes to get the snippet working

* chore: swap out api usage

* chore: more type fixes

i dislike a lot of these

* fix: add JSON body parser to get onboarding working

* fix: use CJS api SDK instead

fixes this error:

```
/Users/kanadg/Code/readmeio/metrics-sdks/packages/node/.api/apis/developers/index.ts:1
import type * as types from './types';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1124:15)
    at Module._compile (node:internal/modules/cjs/loader:1160:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (metrics-sdks/packages/node/dist/src/index.js:55:36)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
```

might be an api bug?

* fix: more typing fixes as a result of writing unit tests

* test: a couple of unit tests

(more to come)

* revert: don't commit example server for now

* fix(prettier): ignore .api directory

* chore: attempt to rebuild lockfiles?

* refactor: don't load in api as nested subpackage thing

* Revert "refactor: don't load in api as nested subpackage thing"

This reverts commit 650a8e3f9a2827bd7500dcabc12d076670a75304.

* Revert "chore: attempt to rebuild lockfiles?"

This reverts commit e260de64fab42e137af5cde6ba8949032975794c.

* chore: try doing this again

* chore: try this instead

* test: migrate nocks over to MSW

* revert: no need to export this

* revert: don't fork tests

* ci: run all tests

* fix: move `.api` directory so TS picks it up

* chore: lint

* chore: lint, migrate new tests over to vitest

* chore: regenerate `api` SDK, this time as TS

* chore: one more lockfile cleanup

have i mentioned i hate this? because i hate this

* chore: one more lockfile refresh my god

* chore: try this lockfile refresh

* chore(lint): my dev environment is gaslighting me

* test: wait there's no way that this is the fix lmao

---------

Co-authored-by: Jon Ursenbach <jon@ursenba.ch>
Co-authored-by: Bill Mill <bill@billmill.org>
Co-authored-by: Aaron Hedges <218751+Dashron@users.noreply.github.com>